---
title: "Business Analytics Competition 2022"
author: 
  - "James Jordan"
  - "Jason Rappazzo<br><br>"
date: "May 6, 2022 <br><br>"
output:
    html_document:
      df_print: paged
      toc: true
      toc_depth: 2
      toc_float: true
      number_sections: true
      highlight: espresso 
---



James Jordan

April 14, 2022


# Project Overview
For our project we have chosen to analyze government COVID-19 related data. As we all know, COVID-19 has impacted just about everyone around the world. Over the past two years, COVID-19 has filled hospitals worldwide and taken countless lives in the process. We want to look at the data to:

- Find trends in government responses in response to the pandemic.

- Discover factors that contribute to COVID-19 deaths.

- Explore the reproductive rate of the virus.

- Look at how the pandemic impacted the growth rates of economies around the world.

#Data
For our data analysis, we are utilizing two large datasets. The first is provided by Oxford titled Oxford COVID Government Response Variables. The second dataset is provided by Bloomberg, for which they have created resiliency scores for the 53 top economies in the world.

On top of these two main datasets, we will also be utilizing GDP growth rate data as well as Google COVID-19 Community Mobility Report to aid in our regression and analysis process.














```


