---
title: "The Effectiveness of Government COVID-19 Policies"
output: html_document
---

# Introduction

For our project, we decided to research the effectiveness of Government COVID-19 policies throughout the pandemic. There were several motivations for wanting to look into this topic. First and foremost, this topic was presented to us by Manhattan College for the annual Business Analytics Competition that they host. For this competition we were tasked with looking into different data sets provided to us by Bloomberg and Oxford, and drawing conclusions from these datasets. The guiding questions that we were presented with are as follows:

- What have we learned about facing the effects of a pandemic, globally?

- Are we better prepared for the next health crisis?

- What data did the Bloomberg and Oxford studies use? How can we characterize resposnes? What is the range of resposnes across countries? Based on our analysis what advice can we give our colleagues in other countries?

Not only were these topic interesting to us... we were also enticed by the chance at winning a cash prize if we placed top 3 in the final round of the competition. While we fell a little short of this goal, we still qualified for the final round, and placed 9th out of 34 teams competing.

Another motivation to look into this topic was how COVID-19 has greatly effected my personal life, and my partners personal life, as we are both students and athletes here at SUNY Geneseo. COVID-19 and the policies presented to us by the government have been a road bump in our busy college careers for about 2 years now, so looking into the best ways to approach a pandemic such as COVID-19 was immediately interesting to both of us. With that being said, part of the motivation to research this topic was to hopefully uncover indicators of successful practices regarding containing the spread of virus, minimizing the fatality of the virus, all while minimizing social and economic impacts. While there is no indication that a pandemic such as COVID-19 will hit again in the near future, it is best to at least begin to look into how we can contain such a catasrophe. There was no indication that COVID-19 would be so harmful, indicating that something like this could happen any day with no prior indication.

## Overview of Modeling Techniques
**Clutsering Analysis:** Grouping data with similar outcomes. The goal of our clustering analysis was to discover countries that had similar government respomses to the COVID-19 Pandemic

**Principal Compononent Analysis:** The princiapl components describe the hyperellipsoid in N-space that roughly bounds the data.

**Pooled Ordeinary Least Squrae:** Normal liner regression model fitted using the OLS technique on a flattened version of the panel data set.

**Fixed Effect Linear Regression:** Statistical regression model which is useful for working with panel data. Panel data allows us to control for variables that we cannot observe or measre such a cultural factors or differences in social norms across countries 


# Data
The data we utilized for our research included two large datasets, one from Oxford and one from Bloomberg. The data presented to us from Oxford was titles "Oxford COVID Government Response Variables". The dataset given to us from Bloomberg was a resiliency ranking that Bloomberg compiled of the top 53 ecoonomies in the world. We also utilized the Google COVID-19 Community Mobility Report to aid in our regression and analysis process.

## Oxford

Oxford's goal is to track COVID-19 policy data and compare each countrie's responses/policies. The data includes 180 countries, utilizing 23 indicators. Collection of the data began January 1st of 2020.
```{r, warning = FALSE, echo=FALSE, message=FALSE}
library(tidyverse)
oxford <- "https://raw.githubusercontent.com/OxCGRT/covid-policy-tracker/master/data/OxCGRT_latest.csv"

oxford <- read_csv(oxford)
oxford <- rename(oxford, country = CountryName)

rmarkdown::paged_table(oxford)
```

### Inidicators
There are a total of 21 live indicators in the dataset that are updated daily

**Containment and Closure Policies:** C1-C8

**Economic Policies:** E1-E4

**Health System Policies:** H1-H8

**Vaccine Policies:**: V1-V4

## Policy Indices

**Overall Government Response Index:** Calculated using ordinal indicators 

**Containment and Health Index** Combines lockdown restricstions and closure measures with health and variables such as testing policy, contact tracing, etc. Calculated using all ordinal containment and closure policy indicators and health system policy indicators.

**Stringency Index:** Measures the strictness of lockdown style. Calculated using all odrinal containment and closure policy indicators, plus an indicator recording public information campaigns

**Economic Support Index:** Measures income support and debt relief. Calculated using all ordinal economic policy indicators.

**Risk of Openness Index:** Based on the reccomendations set out by the World Health organization of measures that should be put in place before COVID-19 response policies can be safely relaxed

### Calculation of Policy Indices

Policy indices are averages of the individual component indicators

## Bloomberg's Data 

Bloomberg created resiliency rankings for the 53 largest economies in the world. A country's rank is based on their success of controlling the virus with the least amount of social economic disruptions.

**Reopening Group:** Vaccine Doses per 100 people, Lockdown Severity, Flight Capacity, Vaccinated Travel Routes.

**Covid Status Group:** 1-Month Cases per 100k, 3-Month Case Fatality Rate, and Deaths Per 1 Million.

**Quality of Life Group:** Community Mobility, 2022 GDP Growth Forecast, Universal Healthcare Coverage, Human Development Index.

### Ranking Mehthod

Bloomberg used the "Max-Min" method where a score of 100 indicates the best performance, while 0 indicates the worst. The final score was then determined by averaging each country's performances across all 12 indicators with equal weight.






